export const authConstant={
    USER_REGISTER:'USER_REGISTER',
    USER_LOGIN:'USER_LOGIN',
    USER_LOGOUT:'USER_LOGOUT'

}

export const productConstant={
    PRODUCT_ADD:'PRODUCT_ADD',
    PRODUCT_EDIT:'PRODUCT_EDIT',
    PRODUCT_DELETE:'PRODUCT_DELETE',
    PRODUCT_ALL:'PRODUCT_ALL',
    PRODUCT_VIEW:'PRODUCT_VIEW',
    PRODUCT_VIEW_FAIL:'PRODUCT_VIEW_FAIL',
    PRODUCT_DETAILS:'PRODUCT_DETAILS',
    PRODUCT_DETAILS_VIEW:'PRODUCT_DETAILS_VIEW',
    PRODUCT_DETAILS_VIEW_FAIL:'PRODUCT_DETAILS_VIEW_FAIL',
    PRODUCT_CATAGORY:"PRODUCT_CATAGORY",
    PRODUCT_SUBCATAGORY:"PRODUCT_SUBCATAGORY"
}

export const cartConstant={
       ADD_FROM_CART:' ADD_FROM_CART',
       REMOVE_FROM_CART:'REMOVE_FROM_CART',
        CART_INCREASE:'CART_INCREASE',
        CART_DECREASE:'CART_DECREASE',
        DELETE_FROM_CART:' DELETE_FROM_CART',
}
